In [1]:
import pandas as pd
from sqlalchemy import create_engine

### Extract CSVs into DataFrames

In [2]:
players_file = "resources/players_20.csv"
players_df = pd.read_csv(players_file)
players_df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

## Transform Players File

In [3]:

# Select columns for DataFrame to import into Players SQL Table
players_cols = ["sofifa_id", "player_url", "short_name", "long_name", "age", "dob", "height_cm", "weight_kg", "nationality", "club",
"overall", "potential", "value_eur", "wage_eur", "player_positions", "preferred_foot"]

players_transformed= players_df[players_cols].copy()

players_transformed.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,preferred_foot
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,94,95500000,565000,"RW, CF, ST",Left
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,93,58500000,405000,"ST, LW",Right
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,92,105500000,290000,"LW, CAM",Right
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,93,77500000,125000,GK,Right
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",Right

In [4]:
# Select columns for DataFrame to import into Player_skill SQL Table
player_skill_cols = ["sofifa_id", "international_reputation", "weak_foot", "skill_moves", "work_rate", "body_type", "real_face", "release_clause_eur", "player_tags", "team_position", "team_jersey_number", "loaned_from",
"joined", "contract_valid_until", "nation_position", "nation_jersey_number", "pace", "shooting", "passing", "dribbling", "defending", "physic",
"gk_diving", "gk_handling", "gk_kicking", "gk_reflexes", "gk_speed", "gk_positioning", "player_traits", "attacking_crossing", "attacking_finishing",
"attacking_heading_accuracy", "attacking_short_passing", "attacking_volleys", "skill_dribbling", "skill_curve", "skill_fk_accuracy", "skill_long_passing", "skill_ball_control",
"movement_acceleration", "movement_sprint_speed", "movement_agility", "movement_reactions", "movement_balance", "power_shot_power", "power_jumping", "power_stamina",
"power_strength", "power_long_shots", "mentality_aggression", "mentality_interceptions", "mentality_positioning", "mentality_vision", "mentality_penalties", "mentality_composure",
"defending_marking", "defending_standing_tackle", "defending_sliding_tackle", "goalkeeping_diving", "goalkeeping_handling", "goalkeeping_kicking", "goalkeeping_positioning", "goalkeeping_reflexes"]

player_skill_transformed= players_df[player_skill_cols].copy()

player_skill_transformed.head()

,sofifa_id,international_reputation,weak_foot,skill_moves,work_rate,body_type,real_face,release_clause_eur,player_tags,team_position,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,158023,5,4,4,Medium/Low,Messi,Yes,195800000.0,"#Dribbler, #Distance Shooter, #Crosser, #FK Sp...",RW,...,75,96,33,37,26,6,11,15,14,8
1,20801,5,4,5,High/Low,C. Ronaldo,Yes,96500000.0,"#Speedster, #Dribbler, #Distance Shooter, #Acr...",LW,...,85,95,28,32,24,7,11,15,14,11
2,190871,5,5,5,High/Medium,Neymar,Yes,195200000.0,"#Speedster, #Dribbler, #Playmaker , #Crosser,...",CAM,...,90,94,27,26,29,9,9,15,15,11
3,200389,3,3,1,Medium/Medium,Normal,Yes,164700000.0,NaN,GK,...,11,68,27,12,18,87,92,78,90,89
4,183277,4,4,4,High/Medium,Normal,Yes,184500000.0,"#Speedster, #Dribbler, #Acrobat",LW,...,88,91,34,27,22,11,12,6,8,8

In [5]:
### Capture unique countries for Country table
country_cols = ["nationality"]

countries_transformed= players_df[country_cols]

countries_transformed.reset_index(inplace=True)
countries_transformed.rename(columns={"nationality": "country_name", "index": "country_id"}, inplace=True)

countries_transformed.head()

C:\Users\cruzm\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

   country_id country_name
0           0    Argentina
1           1     Portugal
2           2       Brazil
3           3     Slovenia
4           4      Belgium

### Create Database Connection

In [6]:
#modify connection string using local database id and password 
connection_string = "postgres:postgres@localhost:5432/fifa_db"
engine = create_engine(f'postgresql://{connection_string}')

### Load DataFrames into SQL Database

In [7]:
#Import dataframes into SQL tables, players, player_skill, country
players_transformed.to_sql(name='players', con=engine, if_exists='append', index=False)
player_skill_transformed.to_sql(name='player_skill', con=engine, if_exists='append', index=False)
countries_transformed.to_sql(name='country', con=engine, if_exists='append', index=False)

In [8]:
#confirm players table
pd.read_sql_query('select * from players', con=engine).head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,preferred_foot
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,94,95500000,565000,"RW, CF, ST",Left
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,93,58500000,405000,"ST, LW",Right
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,92,105500000,290000,"LW, CAM",Right
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,93,77500000,125000,GK,Right
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",Right

In [9]:
#confirm player_skill table
pd.read_sql_query('select * from player_skill', con=engine).head()

,sofifa_id,international_reputation,weak_foot,skill_moves,work_rate,body_type,real_face,release_clause_eur,player_tags,team_position,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,158023,5,4,4,Medium/Low,Messi,Yes,195800000.0,"#Dribbler, #Distance Shooter, #Crosser, #FK Sp...",RW,...,75,96,33,37,26,6,11,15,14,8
1,20801,5,4,5,High/Low,C. Ronaldo,Yes,96500000.0,"#Speedster, #Dribbler, #Distance Shooter, #Acr...",LW,...,85,95,28,32,24,7,11,15,14,11
2,190871,5,5,5,High/Medium,Neymar,Yes,195200000.0,"#Speedster, #Dribbler, #Playmaker , #Crosser,...",CAM,...,90,94,27,26,29,9,9,15,15,11
3,200389,3,3,1,Medium/Medium,Normal,Yes,164700000.0,None,GK,...,11,68,27,12,18,87,92,78,90,89
4,183277,4,4,4,High/Medium,Normal,Yes,184500000.0,"#Speedster, #Dribbler, #Acrobat",LW,...,88,91,34,27,22,11,12,6,8,8

In [10]:
#confirm country table
pd.read_sql_query('select * from country', con=engine).head()

   country_id country_name
0           0    Argentina
1           1     Portugal
2           2       Brazil
3           3     Slovenia
4           4      Belgium